run:
  concurrency: 16
  timeout: 5m
linters:
  fast: false
  disable:
    - lll
    - exportloopref
    - containedctx
    - mnd
    - cyclop
    - exhaustruct
    - nolintlint
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - tagalign
    - gosmopolitan
    - tagliatelle
    - ireturn
    - varnamelen
    - maintidx
  enable-all: true