run:
  concurrency: 16
  timeout: 5m
linters:
  fast: false
  disable:
    # deprecated
    - exportloopref
    # Неиспользуемые
    - exportloopref
    - containedctx
    - cyclop
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gosmopolitan
    - ireturn
    - lll
    - mnd
    - nolintlint
    - nonamedreturns
    - tagalign
    - tagliatelle
    - varnamelen
  enable-all: true