version: 1
linters:
  enable-all: true
  disable:
    - containedctx
    - dupword
    - exhaustruct
    - funlen
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nolintlint
    - tagalign
    - tagliatelle
    - varnamelen
    - cyclop
    - gocognit

linters-settings:
  gofmt:
    simplify: true
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/vynovikov/stock-interactor

exclude:
  - third_party$
  - builtin$
  - examples$
