run:
  timeout: 5m
linters:
  fast: false
  disable:
    - lll
    - exportloopref
    - containedctx
    - cyclop
    - exhaustruct
    - nolintlint
    - funlen
    - nonamedreturns
    - gochecknoglobals
  enable-all: true