# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: interactor.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'interactor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10interactor.proto\x12\ninteractor\"`\n\x0eHistoryRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08interval\x18\x02 \x01(\t\x12\x16\n\x0e\x66rom_timestamp\x18\x03 \x01(\x03\x12\x14\n\x0cto_timestamp\x18\x04 \x01(\x03\"6\n\x0fHistoryResponse\x12#\n\x07\x63\x61ndles\x18\x01 \x03(\x0b\x32\x12.interactor.Candle\"c\n\x06\x43\x61ndle\x12\x11\n\topen_time\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x32Y\n\x0eHistoryService\x12G\n\nGetHistory\x12\x1a.interactor.HistoryRequest\x1a\x1b.interactor.HistoryResponse0\x01\x42<Z:github.com/trading-bot/stock-interactor/internal/api/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interactor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/trading-bot/stock-interactor/internal/api/pb;pb'
  _globals['_HISTORYREQUEST']._serialized_start=32
  _globals['_HISTORYREQUEST']._serialized_end=128
  _globals['_HISTORYRESPONSE']._serialized_start=130
  _globals['_HISTORYRESPONSE']._serialized_end=184
  _globals['_CANDLE']._serialized_start=186
  _globals['_CANDLE']._serialized_end=285
  _globals['_HISTORYSERVICE']._serialized_start=287
  _globals['_HISTORYSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
